# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: publish
  type: boolean
  default: false

jobs:
- job: publish_rust_crates
  displayName: Package or publish Rust crates
  pool:
    name: Azure-Pipelines-1ESPT-ExDShared
    image: windows-2022
    os: windows
  steps:
  - checkout: self

  - template: Rust.Toolchain.Public.yml@self
    parameters:
      targetTriple: x86_64-pc-windows-msvc

  - template: Cargo.Setup.Private.yml@self

  - task: PowerShell@2
    displayName: Process mxc-sdk crate closure
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)/scripts/ci/Invoke-MxcSdkCratePublish.ps1
      ${{ if eq(parameters.publish, true) }}:
        arguments: -Mode Publish -Registry Mxc-Azure-Feed
      ${{ else }}:
        arguments: -Mode Package -Registry Mxc-Azure-Feed
      pwsh: true
      workingDirectory: $(Build.SourcesDirectory)
